name: Update Pr with Jira
on:
  pull_request:
    types: [opened]
  
jobs:
  update_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check Branch
        id: check-branch
        run: |
          if [[ ${{ github.head_ref }} =~ ^[A-Za-z]+-[0-9]+.*$ ]]; then
              echo ::set-output name=match::true
          fi
      - uses: tzkhan/pr-update-action@v2
        if: steps.check-branch.outputs.match == 'true'
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          base-branch-regex: '[A-Za-z\d-_.\\/]+'
          head-branch-regex: '^([A-Za-z])+-\d+'
          title-template: '%headbranch%'
          body-template: |
            Jira issue: [%headbranch%](https://levarne.atlassian.net/browse/%headbranch%)
            ---
          body-update-action: 'prefix'
          body-uppercase-base-match: false
